name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: |
          npm install

      - name: Run Prettier
        run: |
          npx prettier --write .

      - name: Lint code
        run: |
          npm run lint

      - name: Compile TypeScript
        run: |
          npm exec tsc

      - name: Package application
        run: |
          npm run package

      - name: Run tests
        run: |
          npm test
